### PR TITLE
Features/2 readme update

### PR DESCRIPTION
**Pull request by smudge202**
I hope I haven't gone too far with the updates. I moved some of the links down to the bottom to make the file easier to read while editing, added the info mentioned regarding test automation, and merged with your generate step def's update.

I also made a minor amendment to the .sln as per [David Fowler's recommendations](https://gist.github.com/davidfowl/ed7564297c61fe9ab814) and made the readme (and licence) available from with the solution under a `docs` virtual directory. Hopefully that's ok?  Feel free to drop that change (or let me know and I'll revert the respective hunk).

### CODE REVIEW

**Comment by stajs** [comment]
Cool, I'll merge your PR to get your doc updates (thanks!), but I'll back out these two things afterwards:
1. It feels weird having to scroll to the bottom of the README and find the right link so I'll add them back in.
2. I don't think that recommendation is from a Visual Studio solution point of view (e.g. you wouldn't include your `.gitignore` in your solution) so I'll revert the solution change.

Closes #2.

**Comment by smudge202** [comment]
I'll back those changes out as part of my next PR (incoming) if that's ok? (save on merge conflict).

**Comment by smudge202** [comment]
I've just realised that the changes I made to the links totally didn't work in GFM! I see what you mean now; you shouldn't need to scroll to the bottom. I probably needed to add an additional line space between content and links or I've used tabs instead of spaces. GFM can be a little fickle.

**Comment by stajs** [comment]
Sheeit, I just manually backed out those changes. Ah well, it shouldn't be too hard to merge your other PR.

**Pull request merged**
