### PR TITLE
Updated handling of Arguments with spaces

### PR DESCRIPTION
**Pull request by dresdor**

### CODE REVIEW

**Review by stajs — CHANGES_REQUESTED** [review]
Why is this file being added at the repo root, but there is still the old file under the src folder?

**Comment by stajs** [comment]
Why is it merging from an `unknown repository`? Did you delete the fork?

image

**Comment by dresdor** [comment]
I will fix it and get a new pull up today.  I had issues rebasing and it must have messed something up.  Anything else about the code that needs cleaned up or just the file placement issue

**Comment by dresdor** [comment]
new pull request https://github.com/stajs/SpecFlow.NetCore/pull/68

**Pull request closed without merging**
