### PR TITLE
Features/8 dnx451 samples

### LINKED ISSUE #8: dnx451 samples
As per feedback on PR #7, it would be good to get the samples updated to run against the dnx451 work. Samples often suffer from chicken vs egg problems whereby updates to the core library need publishing to nuget before the samples can reference the latest changes.

An alternative approach is mentioned in the comments of PR #7 which I'll give a quick try. Otherwise I guess samples will have to wait until publishing each time.

### PR DESCRIPTION
**Pull request by smudge202**
Resolves #8

### CODE REVIEW

**Comment by smudge202** [comment]
As mentioned in previous PRs, this change provides a `nuget.config` that will detect build outputs from the core project, and shows off the `dnx451` compatibility.

**Comment by stajs** [comment]
Sorry to mess you around on this, I'll merge this in because you deserve the credit for getting `dnx451` up in here, but then I'll remove the `NuGet.config` and multiple TFMs.

#### NuGet.config

Happy to have it as a short-term measure for the chicken/egg problem discussed. Once a package is up on NuGet ([`alpha9` is up now](https://www.nuget.org/packages/SpecFlow.Dnx/1.0.0-alpha9)), it should be removed from the sample so that users can just build the sample without having to build the main library. BTW, great idea (much better way to test it than I was using).

#### TFMs

I think for the purpose of samples, it's better to have multiple solutions per TFM. As a user, I have no idea which one it will pick, so better to be explicit and have a single TFM per sample IMO.

**Comment by smudge202** [comment]
No problem regarding the samples. Should probably keep #8 open and I'll PR again this evening if you haven't done it by then. 

Yeah for alpha 9. :)

@dotnetstation: you can use `dnx451` in alpha9. 

You have a twitter handle, @stajs?

**Comment by stajs** [comment]
Yep, re-opened that. I think it auto-closed as a result of your:

> Resolves #8

Feel free to twat me: mostajs. I'm not very active on there at all though.

**Comment by stajs** [comment]
Also, I may have a follow-up question later: #10.

**Pull request merged**
